name: Go
#┌───────────── minute (0 - 59)
#│ ┌───────────── hour (0 - 23)
#│ │ ┌───────────── day of the month (1 - 31)
#│ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#│ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#│ │ │ │ │                                   
#│ │ │ │ │
#│ │ │ │ │
#* * * * *
on:
  schedule:
    - cron: '* 9 * * *'

jobs:
  clone:
    name: Roc Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        env:
          GITHUB_LOGIN: Roc-zhou
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GITHUB_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@github.com:Roc-zhou/get-everyday-trending.git
          cd get-everyday-trending
          chmod 777 main
          ./main
          git config user.name Roc-zhou
          git config user.email roc.zhousir@gmail.com
          git add .
          git commit -m "Update from Github Action"
          git push origin master

      - name: Done
        run: echo 'done'
